# Generated by Django 6.0.4 on 2026-04-20 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoSportivaBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/gallery/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='DjangoSportivaBase.activity')),
            ],
        ),
    ]
