# Generated by Django 6.0.4 on 2026-04-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoSportivaBase', '0002_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='google_maps_address',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
