# Generated by Django 6.0.4 on 2026-04-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoSportivaBase', '0003_activity_google_maps_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='latitude',
            field=models.FloatField(default=41.3483),
        ),
        migrations.AddField(
            model_name='activity',
            name='longitude',
            field=models.FloatField(default=21.554),
        ),
    ]
