# Generated by Django 6.0.4 on 2026-04-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoSportivaBase', '0004_activity_latitude_activity_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='longitude',
        ),
    ]
