# Generated by Django 6.0.4 on 2026-05-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoSportivaBase', '0005_remove_activity_latitude_remove_activity_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='activities', to='DjangoSportivaBase.service'),
        ),
    ]
