# Generated by Django 6.0.4 on 2026-05-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoSportivaBase', '0006_service_activity_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='sportType',
            field=models.CharField(blank=True, null=True),
        ),
    ]
