# Generated by Django 6.0.4 on 2026-05-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoSportivaBase', '0007_activity_sporttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='sportType',
            field=models.CharField(blank=True, null=True),
        ),
    ]
